name: Deploy File via SCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Mostrar el fitxer
        run: cat wow.txt

      - name: Connectar-se via SSH i executar ordres
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: 22
          first_ssh: |
            echo "Ens hem connectat correctament al servidor!"
          scp: |
            wow.txt ${{ secrets.USER }}@${{ secrets.SSH }}:${{ secrets.DOCUMENT_ROOT }}/
          last_ssh: |
            echo "Fitxer enviat correctament a ${{ secrets.DOCUMENT_ROOT }}"
